### ISSUE TITLE
Support rate limit in JS Client

### ISSUE THREAD

**Issue by embbnux** [ringcentral/ringcentral-js-client#14]
Since js-client know which endpoint is called, can we make js-client handle rate limit problem.

JS-client saved rate limit data from last endpoint response.
When call a new endpoint, just check rate limit data. If it will cause rate limit, just wait.

**Comment by kirill-konshin** [comment]
FYI, JS SDK supports rate limited retries https://github.com/ringcentral/ringcentral-js/blob/master/src/platform/Platform.js#L556

**Comment by kirill-konshin** [comment]
In my opinion this should be an optional functionality, client must perform a request immediately when called.

**Comment by embbnux** [comment]
Agree with that, it should be optional.  
Rate limited retries in SDK is for current endpoint request. For client, it should support to queue endpoint request when a previous endpoint call got rate limit.

**Comment by kirill-konshin** [comment]
I don’t think queuing and waiting is a responsibility of JS client, it is a completely separate task and it should be handled by separate library.

Moreover, different endpoints have different limits, so remembering previous rate limit could be wrong.

**Comment by embbnux** [comment]
We can remember different level limits. Such as Light, Heavy. In client code, we can flag every endpoint with level label. So when user create a request, such as `client.account().extension().list()`, client knows if need to queue the request.

**Comment by kirill-konshin** [comment]
If we can include this info in swagger then maybe it’s ok. But I’d rather not implement it anyway because it’s too unpredictable, imagine something goes wrong on client side and requests are throttled, queue quickly becomes bloated with requests and immediately when queue is resumed client will be queued again or the queue will never empty.

I think that client should only send requests and receive responses, if app needs queueing it should be implemented on top of client.

**Comment by Brutalbeard** [comment]
I agree with @embbnux though @kirill-konshin. 

Purpose of SDKs is to make development easier for our clientele. This allows more development teams to have functioning integrations for their specific needs without having to spend weeks learning the intricacies of our platform. 

The JS client library _does_ make our API even _more_ approachable than the standard JS SDK does. And if the standard JS SDK supports automatic rate limiting, I'm strongly of the opinion that the client should as well.

**Comment by kirill-konshin** [comment]
@brutalbeard @embbnux do you have a solution for above mentioned problems with the queue?

Like I said, I think this has to be implemented as separate library so that only clients that would like to opt in will get it. Separation of concerns and single responsibility principle applies for libs too.

**Comment by embbnux** [comment]
Maybe we can provide a default rate limit solution in JS client. And it is closed default. Developers can also pass a rate limit solution to JS client to replace default rate limit.

**Comment by kirill-konshin** [comment]
Give me a good reason to mix functionality of different kinds in one package. But better let’s take this conversation offline.
