### ISSUE TITLE
Device List endpoint not resolving with query parameters

### ISSUE THREAD

**Issue by Brutalbeard** [ringcentral/ringcentral-js-client#16]
Request
`rc_client.account().device().list({
      perPage: 1000,
      page: 1
    })`

Response URI
`"https://platform.devtest.ringcentral.com/restapi/v1.0/account/665144005/device?page=1&perPage=100"`

Looks to be using the standard query params. Using same list function with extensions endpoint and having no issue.

**Comment by kirill-konshin** [comment]
You probably hit max page size limitation. Try `perPage:50` and if it does not work then it's really ignored. Reopen the issue in this case.
