### ISSUE TITLE
How to get account level call logs?

### ISSUE THREAD

**Issue by tylerlong** [ringcentral/ringcentral-js-client#2]
API Endpoint: `/restapi/v1.0/account/{accountId}/call-log`

I think the code below is for extension level call logs:

``` javascript
client.callLog().list().then((calls) => {

    alert(calls.records[0].id);

});
```

How about account level call logs? Any code samples?

**Comment by kirill-konshin** [comment]
Should be a separate endpoint, in spec too

**Comment by grokify** [comment]
Supported in `/src/paths/Account.ts`
